# NumPy

## 속도를 늘리는 방법
1. HW 업그레이드 - GPU / GPGPU / 분산컴퓨팅   (돈이 많이든다ㅠ)
2. Compiler 

- Cython(C처럼 자료형태를 지정해야함. 컴파일러. C-Python 중간쯤. C속도에 근접하게 나옴.단, 문법이 python이랑 다름)
- PyPy (Python으로 만든 Python. 최적화되어 Python보다 5배 빠름. Python과 동일문법. 단 서드파티 라이브러리/호환성 이슈)
3. Glue language : 다른 언어에 잘 붙는다. -> 병목현상이 일어나는 부분 조정 가능.(공식적으로 Python은 C에 붙이게 되어있음.)
4. 알고리즘/자료구조 : 같은 연산이지만 코드 구조로 속도를 올려줌(계산)


=> 이를 모두 충족시킨 것: NumPy : 속도개선에 있어서 혁신적임.(Glue Language, 알고리즘 측면에서 빠름. 파이썬의 20배정도)

## 속도는 민감하고 중요한 문제다

NumPy쓰는 이유: 1. 속도가 빠름 2. 복잡한 계산을 보다 빠르고 쉽게 할 수 있다

Numpy 기반: pandas, 싸이킷, tensorFlow

### 왜 속도가 빠를까? -> '벡터화(Vectorization)' 
### but, GPU지원 안해서 Tensor를 만듬

Array : CS 용어

Vector : 수학적 용어(여러 개의 데이터를 한 묶음으로 만드는 애.

Loop가 없다.(속도가 느리기 때문) -> 1. iterator/generator 2. Comprehension 3. Recursion 4. map/filter/reduce(high-order function)

==> 벡터화 라고 한다.

## ★Array Programming★

### 단, 숫자가 작으면 느리기 때문에(클땐 빠르다) 항상 쓰진 않는다

1차원 벡터는 방향이 있지만, 여기선 없다고 친다.

2차원 Matrix

3차원 3D Array = 3rd Demension Tensor

N차원 ND Array = N차원 Tensor

## => 어떤 현상을 벡터화하는 것이 핵심

이미지는 2차원데이터지만 색상/시간 등을 추가하여 3차원/4차원으로 표현 가능

In [1]:
import numpy as np

In [5]:
len(dir(np))

#수많은 내장함수...
#수학함수가 많다
#대문자가 먼저 나옴 -> 아스키코드 순서.(관례상 파이썬은 상수(_재할당) 가 없다. 그러나 대문자가 있으면 상수로 씀)

622

In [6]:
# 데이터를 생성하는 방법
# 1. 인스턴스 2. literal: 파이썬 고유 타입만 지원.
# '3.' :(디자인패턴) Factory Method : 클래스를 이용하여 인스턴스화 하지 않고, 다른 함수를 빌어와 쓴다. 
# ex: array

In [7]:
import array
#파이썬 공식 라이브러리에도 있다. (..?)
# '일반적으로' 호모지니어스 타입을 읽는다. str, range : 다음 데이터타입을 체크할 필요가 없다 -> 빠르다.
# np.array != python array. 

In [9]:
#array(object, dtype=None, copy=True, order='K'_정렬순서:C/Forthran방식 다 지원, subok=False, ndmin=0)
#호모지니어스

a = np.array(1)
a

array(1)

In [10]:
a = np.array([1,2])
a

array([1, 2])

In [12]:
a = np.array((1,2))
a

# 튜플로 넣어도 리스트로 나온다. -> Mutable. => Shallow copy/Deep copy 신경써야 한다.

array([1, 2])

In [13]:
type(a)
# 원래 이름은 ndarray. 

numpy.ndarray

In [14]:
a = np.array([[1,2],[3,4]])
a


# Matrix

array([[1, 2],
       [3, 4]])

In [16]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a

# 3darray = tensor
# 사이사이에 공백이 들어감.

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [19]:
# 인스턴스

n = np.ndarray(0)
n
# dtype=float64
# 호모지니어스인데, 데이터타입이 중요한 이유: 

array([], dtype=float64)

In [20]:
b = np.array(['1',2,3])
b
#dtype='<U1'    #문자열로 다 바뀌었다. -> 같은 데이터타입으로 바꿔준다.
#여기서 꺽쇠(<) : 리틀 앤디언/빅 앤디언 방식 지원.(C방식,포트란방식)
# '<U1' : 리틀 앤디언

array(['1', '2', '3'], dtype='<U1')

In [23]:
n = np.ndarray([0,'1'])
# Factory Method가 이럴때 좋다.

TypeError: 'str' object cannot be interpreted as an integer

In [24]:
vars(a)
# __dict__를 지정해야함.

TypeError: vars() argument must have __dict__ attribute

In [30]:
a = np.array([[1,2],[3,4]])
print(a, a.ndim) #차원 수 #2차원

[[1 2]
 [3 4]] 2


In [27]:
len(a)

2

In [28]:
a.shape    #n행, n열
# 중요: 행렬 연산할 때 모양 맞춰야하기 때문에.(앞열/뒷행)

(2, 2)

In [29]:
a.flags

# C_CONTIGUOUS : True
# F_CONTIGUOUS : False
# C방식/포트란 방식
# C : 1,2,3,4, (옆으로 저장) -> 가로방향
# 포트란 : 1 3 2 4(지그재그 저장) -> 세로방향

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [31]:
a.size # 원소의 개수

4

In [32]:
a.itemsize  #비트 수

4

In [33]:
a.dtype

dtype('int32')

In [34]:
b = np.array([[1,2],[3,4]])
x = [1,2,3,4]
y = [2,3,4,5]
x+y    #뒤에 추가됨.

[1, 2, 3, 4, 2, 3, 4, 5]

In [35]:
a + b     # [[1,2,],[3,4]] 

#엘리먼트 끼리 더해줌.((1,1)+(1,1)) -> 더 쉽게 벡터연산을 해줌.

array([[2, 4],
       [6, 8]])

In [37]:
x = [1,2,3,4]
y = [2,3,4,5]
[a+b for a,b in zip(x,y)]

[3, 5, 7, 9]

In [38]:
a-b

array([[0, 0],
       [0, 0]])

In [39]:
a*b

array([[ 1,  4],
       [ 9, 16]])

In [40]:
a/b

array([[1., 1.],
       [1., 1.]])

In [42]:
# Element wise 방식.

a.T #(행과 열을 바꾸는것)

array([[1, 3],
       [2, 4]])

## NumPy :  R을 베껴왔다.
## SciPy 참고

## strides : 일렬 구조를 일렬씩 잘라서 사람에게 다차원으로 보여주는 것.

In [43]:
a.strides
# (8, 4) ->(최대공약수로 나누면) (2,1) => 2개가 한 행이다.

(8, 4)

In [ ]:
# NumPy 가 빠른이유: 1. C로 짬 2. 효율적인 자료구조

## 자료형
### 파이썬/C의 자료형 모두 지원.. 해주지만 여기서는 무조건 int64/float64만 다룬다.(빅데이터 할거니까)

In [44]:
# 데이터형태 지정하기 / 확인하기 / 변환하기

## 파이썬 int 특징: 오버플로우 없다. 무한정 증가 가능

In [45]:
# 앞에 언더바 하나: 관례상 private     # from * 쓸때는 _ 임포트.
# 앞에 언더바 2개: 맹글링. (dir할때 안나옴.)
# __가나다__ : 매직 메소드

In [48]:
a = np.array([[1,2],[3,4]], dtype='i2')# 단축표현
b = np.array([[1,2],[3,4]], dtype='u1')
a

array([[1, 2],
       [3, 4]], dtype=int16)

In [49]:
b

array([[1, 2],
       [3, 4]], dtype=uint8)

In [52]:
np.sctypeDict.keys()

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 9, 'uintp', 'P', 10, 'long', 'l', 7, 'L', 8, 'longlong', 'q', 'ulonglong', 'Q', 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'Bool', 'b1', 'int64', 'Int64', 'i8', 'uint64', 'Uint64', 'u8', 'float16', 'Float16', 'f2', 'float32', 'Float32', 'f4', 'float64', 'Float64', 'f8', 'complex64', 'Complex32', 'c8', 'complex128', 'Complex64', 'c16', 'object0', 'Object0', 'bytes0', 'Bytes0', 'str0', 'Str0', 'void0', 'Void0', 'datetime64', 'Datetime64', 'M8', 'timedelta64', 'Timedelta64', 'm8', 'int32', 'Int32', 'i4', 'uint32', 'UInt32', 'u4', 'UInt64', 'int16', 'Int16', 'i2', 'uint16', 'UInt16', 'u2', 'int8', 'Int8', 'i1', 'uint8', 'UInt8', 'u1', 'complex_', 'int0', 'uint0', 'single', 'csingle', 'singlecomplex', 

In [50]:
len(np.sctypeDict)

152

In [51]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/David/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/David/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/David/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/U

# 우리가 쓸건? 
# int64, float64, float128만 사용할거다

In [53]:
# Strides(12,4) : 4x1 x 4bytes

In [54]:
# 64bit = 8bytes
# 32bit = 4bytes

# axis, strides 개념.

In [56]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
a.reshape(2,5)    #모양을 바꿀 수 있다.(행, 열)
#메모리 공유가 아니다. -> 재할당 해야함.

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [60]:
a
# reshape이 적용안됨.
# 뮤터블 3가지.
# NumPy: 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
a = a.reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [64]:
a.sum()
#(axis=None, dtype=None, out=None, keepdims=False)
# a.shape = 2,5

45

In [65]:
a.sum(axis=0)
# 같은 열끼리 덧셈
# [1,2,3]
# +
# [4,5,6]

array([ 5,  7,  9, 11, 13])

In [66]:
a.sum(axis=1)
# 같은 행끼리 덧셈
# [1,2,3] +
# [4,5,6] +

array([10, 35])

In [68]:
a.min(axis=0)

array([0, 1, 2, 3, 4])

In [69]:
a.min(axis=1)

array([0, 5])

In [70]:
%time sum(x for x in range(1000000))

Wall time: 172 ms


499999500000

In [71]:
%time np.sum(np.arange(1000000))

Wall time: 4.43 ms


1783293664

# 데이터 만들기

In [75]:
a = np.zeros(shape=(3,4))
a
# 3행 4열
# zeros(shape, dtype=float, order='C')

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
b = np.ones((3,4))    #1로 만들기
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [79]:
c = np.full((3,4), 6)    #한 숫자로 다 만들고 싶을 때
c

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [81]:
d = np.full_like(a, 9)     #a랑 같은 모양에 다른 숫자.
d                          #행렬 연산시 모양(shape) 중요.

array([[9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.]])

In [82]:
b = np.eye(3)
b   #단위행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
c = np.identity(4)
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [87]:
b = np.tri(3)       #상삼각행렬
b

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [88]:
b = np.triu((3,3))    #하삼각행렬
b

array([[3, 3],
       [0, 3]])

In [89]:
b.T  #전치행렬

array([[3, 0],
       [3, 3]])

In [90]:
np.transpose(b)

array([[3, 0],
       [3, 3]])

## arange랑 비슷하지만, 구간별로 잘라서 만들 수 있는 것.

In [91]:
d = np.linspace(0,100)
d

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [93]:
e = np.logspace(1,100)   #로그로 잘라줌.
e

array([1.00000000e+001, 1.04811313e+003, 1.09854114e+005, 1.15139540e+007,
       1.20679264e+009, 1.26485522e+011, 1.32571137e+013, 1.38949549e+015,
       1.45634848e+017, 1.52641797e+019, 1.59985872e+021, 1.67683294e+023,
       1.75751062e+025, 1.84206997e+027, 1.93069773e+029, 2.02358965e+031,
       2.12095089e+033, 2.22299648e+035, 2.32995181e+037, 2.44205309e+039,
       2.55954792e+041, 2.68269580e+043, 2.81176870e+045, 2.94705170e+047,
       3.08884360e+049, 3.23745754e+051, 3.39322177e+053, 3.55648031e+055,
       3.72759372e+057, 3.90693994e+059, 4.09491506e+061, 4.29193426e+063,
       4.49843267e+065, 4.71486636e+067, 4.94171336e+069, 5.17947468e+071,
       5.42867544e+073, 5.68986603e+075, 5.96362332e+077, 6.25055193e+079,
       6.55128557e+081, 6.86648845e+083, 7.19685673e+085, 7.54312006e+087,
       7.90604321e+089, 8.28642773e+091, 8.68511374e+093, 9.10298178e+095,
       9.54095476e+097, 1.00000000e+100])

In [96]:
e = np.empty((4,2))
e
# 더미 데이터

array([[0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 3.16202013e-321],
       [2.22522596e-306, 2.33419537e-312]])

## 추출

In [97]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [100]:
# indexing, slicing (sequence타입: 순서 중요) / key

In [101]:
a[1][3]

8

In [103]:
a[1,3]

8

In [105]:
a[:,4]    # 모든 행에서 5번째.(특정 열/행 뽑아내기)

array([4, 9])

In [106]:
a = np.arange(27).reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [109]:
a[1,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [110]:
a[1,...]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [113]:
n = np.arange(36).reshape(6,6)
n

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [119]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
a[a>3]    #조건식도 집어넣을수있다. (ㄷㄷ)

array([4, 5, 6, 7, 8, 9])

In [123]:
a[(a>3)&(a<7)]
# |(or) 도 사용가능

array([4, 5, 6])

In [127]:
a[[True,True,False,True,True,True,True,True,True,True]]
# True인것만 뽑을 수 있다. -> 마스킹 기법.

array([0, 1, 3, 4, 5, 6, 7, 8, 9])

In [128]:
a>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [132]:
d = np.arange(15).reshape(5,3)
d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [133]:
#Fancy Indexing
d[[1,2]]

array([[3, 4, 5],
       [6, 7, 8]])

In [134]:
d[[-1,-2]]

array([[12, 13, 14],
       [ 9, 10, 11]])

In [135]:
#ex
a = np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [136]:
a[[1,3]][:,1]

array([3, 7])

In [137]:
x = np.arange(36).reshape(6,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [138]:
x[(0,1,2,3,4),(1,2,3,4,5)]      # (0,1) (1,2) (2,3) ...

array([ 1,  8, 15, 22, 29])

In [ ]:
#### mask = array([1,0,1,0,0,1], dtype=bool

In [143]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [144]:
a[0]

array([0, 1, 2, 3, 4])

In [145]:
a[1,3:5]

array([8, 9])

In [146]:
a[:,4]

array([ 4,  9, 14, 19, 24])

In [147]:
a[-2:, -2:]

array([[18, 19],
       [23, 24]])

In [148]:
a[0,1]

1

In [ ]:
a[[]]

In [149]:
b = np.nditer(a)
next(b)

array(0)

In [150]:
def add_(a,b):
    return a+b

x = np.arange(5)
y = np.arange(5)
add_(x,y)

array([0, 2, 4, 6, 8])

In [151]:
3 + np.arange(10)     #브로드캐스팅(BroadCasting): 간단한건 NumPy가 알아서 맞춰줌.
# 엑셀 - 핸들이랑 비슷한 개념처럼 보임.

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## ufunc  : Universal Function (보편적인)

In [152]:
abs(-1)  #절댓값

1

In [153]:
abs([-1,1,2])

TypeError: bad operand type for abs(): 'list'

In [154]:
np.abs([-1,2,1])

array([1, 2, 1])

In [155]:
np.ceil([2.9,1,2,3,0.3])
# ufunc : 여러개 동시에 계산도 되고 한개만 집어넣어도 되고...

array([3., 1., 2., 3., 1.])

In [156]:
np.info(np.ceil)

ceil(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the ceiling of the input, element-wise.

The ceil of the scalar `x` is the smallest integer `i`, such that
`i >= x`.  It is often denoted as :math:`\lceil x \rceil`.

Parameters
----------
x : array_like
    Input data.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
y : ndarray or scalar
    The ceilin

In [157]:
from scipy.special import factorial

In [159]:
factorial(10, exact=True)

3628800

In [161]:
factorial([3,4,5])

array([  6.,  24., 120.])

In [162]:
np.info(factorial)

 factorial(n, exact=False)

The factorial of a number or array of numbers.

The factorial of non-negative integer `n` is the product of all
positive integers less than or equal to `n`::

    n! = n * (n - 1) * (n - 2) * ... * 1

Parameters
----------
n : int or array_like of ints
    Input values.  If ``n < 0``, the return value is 0.
exact : bool, optional
    If True, calculate the answer exactly using long integer arithmetic.
    If False, result is approximated in floating point rapidly using the
    `gamma` function.
    Default is False.

Returns
-------
nf : float or int or ndarray
    Factorial of `n`, as integer or float depending on `exact`.

Notes
-----
For arrays with ``exact=True``, the factorial is computed only once, for
the largest input, with each other result computed in the process.
The output dtype is increased to ``int64`` or ``object`` if necessary.

With ``exact=False`` the factorial is approximated using the gamma
function:

.. math:: n! = \Gamma(n+1)

Examples


In [164]:
np.iinfo() 
# integer타입에 대한 정보를 알려준다

TypeError: __init__() missing 1 required positional argument: 'int_type'

In [165]:
np.info(np.ufunc)

 ufunc()

Functions that operate element by element on whole arrays.

To see the documentation for a specific ufunc, use `info`.  For
example, ``np.info(np.sin)``.  Because ufuncs are written in C
(for speed) and linked into Python with NumPy's ufunc facility,
Python's help() function finds this page whenever help() is called
on a ufunc.

A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.

Calling ufuncs:

op(*x[, out], where=True, **kwargs)
Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.

The broadcasting rules are:

* Dimensions of length 1 may be prepended to either array.
* Arrays may be repeated along dimensions of length 1.

Parameters
----------
*x : array_like
    Input arrays.
out : ndarray, None, or tuple of ndarray and None, optional
    Alternate array object(s) in which to put the result; if provided, it
    must have a shape that the inputs broadcast to. A tuple of arrays
    (possible only as a keyword argument) must ha

In [ ]:
  x = np.array([5,4,3,2,1,0])
#  np.max(x) / np.where(x>=3) / 
#  np.argmax(x) /        np.argmin(x)

In [168]:
np.where(a>5, 0, 1)    #조건에 맞으면 0쓰고 안맞으면 1써라

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [169]:
np.where(a>4)

(array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4],
       dtype=int64),
 array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       dtype=int64))

In [170]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [171]:
np.max(a)

24

In [172]:
np.argmax(a)  #index

24

In [173]:
np.argmin(a)

0

In [176]:
print(a.argmin(), a.argmax())

0 24


# 메소드로 사용할때는 a.arg---
## 지원하는 함수도 있고 (간혹)안하는 함수도 있으니 혼동하지 말것.

In [177]:
# https://docs.scipy.org/doc/numpy/user/quickstart.html

In [184]:
from numpy import pi

from math import pi as mpi

print(pi, mpi)

3.141592653589793 3.141592653589793


In [182]:
pi == mpi

True

In [185]:
pi is mpi
# 다른 메모리에 있는거니까.
# 값만 같다.

False

In [187]:
# 심화, 중요
np.random.rand(1,2,3,4,5,6)

array([[[[[[0.74161096, 0.60295388, 0.96796749, 0.89766852,
            0.72093646, 0.57605451],
           [0.42360935, 0.52391338, 0.7110311 , 0.95434838,
            0.3188571 , 0.75506944],
           [0.2434766 , 0.02804828, 0.74389169, 0.39238409,
            0.76513778, 0.23162356],
           [0.73884286, 0.5426754 , 0.52498713, 0.86891413,
            0.31592502, 0.47964741],
           [0.16289762, 0.89246729, 0.37893889, 0.56924605,
            0.57483963, 0.56353533]],

          [[0.24801673, 0.22037294, 0.93127096, 0.12844285,
            0.09644472, 0.59729895],
           [0.38880549, 0.85283439, 0.60917729, 0.44734935,
            0.18974976, 0.71684991],
           [0.59748852, 0.06950507, 0.29073629, 0.09531112,
            0.41963321, 0.94836329],
           [0.59312656, 0.59695858, 0.26071851, 0.68736124,
            0.75321571, 0.01570163],
           [0.47821457, 0.90264445, 0.05591265, 0.99300622,
            0.63343113, 0.68877976]],

          [[0.1393945 , 0.

In [188]:
type(...)

ellipsis

In [189]:
dir(...)  
#이거 쓰지 말것.

['__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

In [190]:
vars(...)

TypeError: vars() argument must have __dict__ attribute

In [194]:
float('nan') == np.nan 
# ? => 외워.

False

In [199]:
np.set_printoptions(threshold=np.nan)

# np.set_printoptions(
#     precision=None,
#     threshold=None,
#     edgeitems=None,
#     linewidth=None,
#     suppress=None,
#     nanstr=None,
#     infstr=None,
#     formatter=None,
#     sign=None,
#     floatmode=None,
#     **kwarg,

# )

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

In [202]:
a = np.arange(10).reshape(2,5)

In [204]:
np.newaxis   #결과값이 없다

In [205]:
np.newaxis is None #외워라.

True

In [206]:
np.set_printoptions(threshold=3)

In [207]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [209]:
# A * B : Element끼리 곱
# A @ B : 원래 알고있는 행렬곱    (NumPy 전용)

A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

print(A*B, A@B, end='\n\n')

[[2 0]
 [0 4]] [[5 4]
 [3 4]]



In [211]:
z = np.arange(3)
np.exp(z)

array([1.        , 2.71828183, 7.3890561 ])

In [212]:
np.sqrt(z)

array([0.        , 1.        , 1.41421356])

In [ ]:
# 1. 콤마(행렬분리, 각각)
# 2. ...
# 3. 마스킹
# 4. 조건
# 5. 팬시 인덱싱

In [213]:
a = np.arange(10).reshape(2,5)
a  #2중으로 쌓여있다 [[]]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [214]:
b = a
a[0][0] = 100
#바뀌면 Deep copy, 안바뀌면 Shallow copy
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [215]:
b

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [216]:
c = b.copy()    #shallow copy (in Python)
b[0][0] = -100
b

array([[-100,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [217]:
c    #NumPy는 Deep copy

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [218]:
c = b.view()   #NumPy에서의 Shallow copy
b[0][0] = 200
c

array([[200,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [ ]:
# Deep Copy: 원본 보존.

In [ ]:
# 과제: div.main 안에 있는 링크 크롤링해서 정리하기.

In [ ]:
#https://docs.scipy.org/doc/numpy/user/quickstart.html