## NumPy 쓰는이유? 쉽고 빠르니까~

In [ ]:
# .reshape
# broadcasting : 

In [1]:
import numpy as np

In [3]:
np.lookfor('shape')
# np.info 랑 비슷

Search results for 'shape'
--------------------------
numpy.shape
    Return the shape of an array.
numpy.reshape
    Gives a new shape to an array without changing its data.
numpy.flip
    Reverse the order of elements in an array along the given axis.
numpy.full
    Return a new array of given shape and type, filled with `fill_value`.
numpy.isin
    Calculates `element in test_elements`, broadcasting over `element` only.
numpy.ones
    Return a new array of given shape and type, filled with ones.
numpy.empty
    Return a new array of given shape and type, without initializing entries.
numpy.zeros
    Return a new array of given shape and type, filled with zeros.
numpy.resize
    Return a new array with the specified shape.
numpy.ndarray
    ndarray(shape, dtype=float, buffer=None, offset=0,
numpy.ndindex
    An N-dimensional iterator object to index arrays.
numpy.squeeze
    Remove single-dimensional entries from the shape of an array.
numpy.ma.shape
    Return the shape of an array.

In [4]:
# 연습용 데이터
a = np.array(100)

In [5]:
a #0차...속지말자

array(100)

In [6]:
a = np.array([1,2,3])
a  #1차

array([1, 2, 3])

In [7]:
a = np.array([[1,2,3],[4,5,6]])
a #2차

array([[1, 2, 3],
       [4, 5, 6]])

## 이번 수업의 목표는 이미지처리까지 -> 3차까지만.

In [8]:
a = np.arange(27)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [10]:
a = a.reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [11]:
# 중요한 것: 갯수를 맞춰야 한다
a.shape

(3, 3, 3)

In [12]:
a = a.reshape(3,9)   #mutable function이 아니기 때문에 재할당 해줘야한다. 
a                    #

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [13]:
b = a.reshape(9,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [15]:
b[0][0]=100
b

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11],
       [ 12,  13,  14],
       [ 15,  16,  17],
       [ 18,  19,  20],
       [ 21,  22,  23],
       [ 24,  25,  26]])

In [16]:
a    # ;;;;;
# 이래서 copy 써야한다.

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [17]:
# 기본적으로는 Deep Copy
b = a.reshape(9,3).copy()
b

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11],
       [ 12,  13,  14],
       [ 15,  16,  17],
       [ 18,  19,  20],
       [ 21,  22,  23],
       [ 24,  25,  26]])

In [18]:
b[0][0] = 200
a

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [19]:
# reshape 계산하기 귀찮을 때 => Automatic
b = a.reshape(9,-1)
b

#알아서 바꿔준다.

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11],
       [ 12,  13,  14],
       [ 15,  16,  17],
       [ 18,  19,  20],
       [ 21,  22,  23],
       [ 24,  25,  26]])

In [20]:
b = a.reshape(-1,-1)
# 2개를 동시에 유추할 순 없다. but...

ValueError: can only specify one unknown dimension

In [23]:
b = a.reshape(3,-100)
b
# 마이너스 붙이면 알아서 바꿔준다. 관례상 -1을 써줄뿐.

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [25]:
a.resize((9,3))      #재할당 안해도 자기 자신이 바뀜.    reshape과의 차이점.
a

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11],
       [ 12,  13,  14],
       [ 15,  16,  17],
       [ 18,  19,  20],
       [ 21,  22,  23],
       [ 24,  25,  26]])

In [28]:
a = np.arange(27)
a.resize((3,5))
a    #계산 잘못하면 짤린다..;;

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
a = np.arange(27)
a.resize((3,10))
a    #계산 잘못하면 이상해진다...;;

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26,  0,  0,  0]])

In [31]:
a = np.arange(27)
a.resize((3,-1))   #심지어 이것도 안됨.

ValueError: negative dimensions not allowed

In [ ]:
# 그래서 90%책에는 reshape을 예제로 쓴다. resize는 주의해서 써야한다.

# 배열 분할

- 그냥 분할

- 수평축 분할 (Horizontal split)

- 수직축 분할 (Vertical split)

In [32]:
a = np.arange(27).reshape(3,9)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [34]:
dir(a)
# ...split이 없다?
#function방식에 없으면 메소드 방식으로 간다.

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [35]:
np.split(a)
# 자르는 기준이 있어야 한다.

TypeError: split() missing 1 required positional argument: 'indices_or_sections'

In [36]:
np.split(a,1)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [37]:
np.split(a,2)
# 자르는 기준은 튜플형태

ValueError: array split does not result in an equal division

In [38]:
np.split(a,(1,2))
# 0에서1까지, 1에서2까지, 2에서3까지..?

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [39]:
np.split(a,(2,2))
#0에서2까지, 2에서4까지, 4에서6까지......?

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([], shape=(0, 9), dtype=int32),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [40]:
np.split(a,(2,5))
#0에서2까지, 2에서5사이, 

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([], shape=(0, 9), dtype=int32)]

In [41]:
np.split(a,(-2,5))

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([], shape=(0, 9), dtype=int32)]

In [43]:
np.split(a,(5,5), axis=1)
# array([], shape=(3, 0), dtype=int32),  #요건 구분선

[array([[ 0,  1,  2,  3,  4],
        [ 9, 10, 11, 12, 13],
        [18, 19, 20, 21, 22]]),
 array([], shape=(3, 0), dtype=int32),
 array([[ 5,  6,  7,  8],
        [14, 15, 16, 17],
        [23, 24, 25, 26]])]

In [45]:
#horizontal split
np.hsplit(a, (5,))
# 구분선없이 잘린다.

[array([[ 0,  1,  2,  3,  4],
        [ 9, 10, 11, 12, 13],
        [18, 19, 20, 21, 22]]), array([[ 5,  6,  7,  8],
        [14, 15, 16, 17],
        [23, 24, 25, 26]])]

In [46]:
np.vsplit(a,(2,))
#2행 자를때 쓰는것. 

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [49]:
# 붙이는 것 = stack
b = np.arange(5)
c = np.arange(5,10)

In [50]:
np.stack((b,c))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [51]:
# np.stack(arrays, axis=0, out=None)

In [52]:
np.stack((b,c),1)

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [53]:
np.stack((b,c),0)   #default: axis=0

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
np.vstack((b,c))  #위아래

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
np.hstack((b,c))  #옆으로

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Split --- Stack

In [56]:
# 단축표현
np.r_[b,c]
# == hstack
# row

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.c_[b,c]
# == vstack
# column

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [58]:
np.s_[b,c]
# slicing 객체
# (안할거다)

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [59]:
[1,2,3,4,5,][slice(1,5)]
# == [1,2,3,4,5,][1:5]
# s_

[2, 3, 4, 5]

In [60]:
np.s_[1,3]

(1, 3)

In [62]:
np.arange(10)[np.s_[1]]

1

## 언더바 3총사(slicing)
## r_ c_ s_

In [64]:
np.column_stack([b,c])

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [65]:
np.row_stack([b,c])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# 골치아픈 것..?

In [66]:
a =np.arange(6)
a
#1차원 데이터를 2차원으로 변화시키고 싶다.

array([0, 1, 2, 3, 4, 5])

In [67]:
# 1. reshape
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [68]:
# "원하는게 이게 아니다." [[0,1,2,3,4,5]] 이렇게 하고 싶을땐?
a[np.newaxis]

array([[0, 1, 2, 3, 4, 5]])

In [69]:
np.newaxis is None
#....?

True

In [70]:
a[None]
#??????????
#차원이 확대되었다

array([[0, 1, 2, 3, 4, 5]])

In [71]:
a = a.reshape(2,-1)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [72]:
a[np.newaxis]

array([[[0, 1, 2],
        [3, 4, 5]]])

In [73]:
a
#얘들 각각을 차원화화고싶으면?

array([[0, 1, 2],
       [3, 4, 5]])

In [75]:
a[:,np.newaxis]

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [76]:
a[:,:,np.newaxis]
#모양 바꿀때 이렇게.

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [79]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [80]:
a[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [81]:
# 연산할 때 shape을 맞춰야하기 때문에 변환이 자유자재로 되야한다.
# 그래서 어떤애가 있냐?

In [82]:
np.expand_dims(a,0)
# np.expand_dims(a, axis)

array([[0, 1, 2, 3, 4, 5]])

In [83]:
np.expand_dims(a,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [85]:
#1차원->3차원으로는 증가시킬 수 없다.
#차원을 +1만 가능.

In [86]:
a = np.arange(27).reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [89]:
np.swapaxes(a,0,2)

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [90]:
np.moveaxis(a,0,2)  #x축 <-> y축

array([[[ 0,  9, 18],
        [ 1, 10, 19],
        [ 2, 11, 20]],

       [[ 3, 12, 21],
        [ 4, 13, 22],
        [ 5, 14, 23]],

       [[ 6, 15, 24],
        [ 7, 16, 25],
        [ 8, 17, 26]]])

## 사용자 데이터 타입 만들기
## dtype = (튜플), (튜플) 형태
## Structured Arrays
## DB처럼 활용 가능

In [92]:
 x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],
              dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

In [93]:
x

array([('Rex', 9, 81.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [94]:
x[0]

('Rex', 9, 81.)

In [95]:
x[1]

('Fido', 3, 27.)

In [96]:
#NamedTupe과 유사
from collections import namedtuple

In [97]:
#namedtuple(typename, field_names, *, rename=False, defaults=None, module=None,)

Address = namedtuple('Address',('name','age','weight'))

In [102]:
a1 = Address('Rex',27,81.0)  
#클래스 만드는거랑 유사.
# 클래스이름:Address, ...
a1

Address(name='Rex', age=27, weight=81.0)

In [101]:
print(a1.name, a1.age, a1.weight)

Rex 27 81.0


In [103]:
dir(a1)
# age, name, weight
# count, index -> 튜플에서 튀어나온 애.
# => Namedtuple을 사용하면 빠르게 클래스화 시킬수 있다.

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '_asdict',
 '_fields',
 '_fields_defaults',
 '_make',
 '_replace',
 'age',
 'count',
 'index',
 'name',
 'weight']

In [105]:
print(a1[0],a1[1])
#이름으로도, 인덱스로도 쓸수있다. namedtuple

Rex 27


In [106]:
a1['name']
#기본적으론 튜플이라 이건 안된다.
#key로 접근하는것.

TypeError: tuple indices must be integers or slices, not str

In [109]:
#NumPy -> Structured Arrays는 가능하다.
x['name']

(array(['Rex', 'Fido'], dtype='<U10'), array([9, 3]))

In [112]:
x.name

AttributeError: 'numpy.ndarray' object has no attribute 'name'

In [114]:
'name' in dir(x)

False

## 나만의 데이터 구조를 만들 수 있다

# 불러올 때 NumPy파일로 하는게 좋다. 하지만 복잡스.

In [115]:
import seaborn as sns

In [116]:
tips = sns.load_dataset('tips')
#연습데이터

In [117]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
6          8.77  2.00    Male     No   Sun  Dinner     2
7         26.88  3.12    Male     No   Sun  Dinner     4
8         15.04  1.96    Male     No   Sun  Dinner     2
9         14.78  3.23    Male     No   Sun  Dinner     2
10        10.27  1.71    Male     No   Sun  Dinner     2
11        35.26  5.00  Female     No   Sun  Dinner     4
12        15.42  1.57    Male     No   Sun  Dinner     2
13        18.43  3.00    Male     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
15        21.58  3.92    Male     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
17        16.29  3.71    Male     No   Sun  Dinner     3
18        16.97  3.50  Female     No   Sun  Dinner     3
19        20.65  3.35    Male     No   Sat  Dinner     3
20        17.92  4.08    Male     No   Sat  Dinner     2
21        20.29  2.75  Female     No   Sat  Dinner     2
22        15.77  2.23  Female     No   Sat  Dinner     2
23        39.42  7.58    Male     No   Sat  Dinner     4
24        19.82  3.18    Male     No   Sat  Dinner     2
25        17.81  2.34    Male     No   Sat  Dinner     4
26        13.37  2.00    Male     No   Sat  Dinner     2
27        12.69  2.00    Male     No   Sat  Dinner     2
28        21.70  4.30    Male     No   Sat  Dinner     2
29        19.65  3.00  Female     No   Sat  Dinner     2
..          ...   ...     ...    ...   ...     ...   ...
214       28.17  6.50  Female    Yes   Sat  Dinner     3
215       12.90  1.10  Female    Yes   Sat  Dinner     2
216       28.15  3.00    Male    Yes   Sat  Dinner     5
217       11.59  1.50    Male    Yes   Sat  Dinner     2
218        7.74  1.44    Male    Yes   Sat  Dinner     2
219       30.14  3.09  Female    Yes   Sat  Dinner     4
220       12.16  2.20    Male    Yes   Fri   Lunch     2
221       13.42  3.48  Female    Yes   Fri   Lunch     2
222        8.58  1.92    Male    Yes   Fri   Lunch     1
223       15.98  3.00  Female     No   Fri   Lunch     3
224       13.42  1.58    Male    Yes   Fri   Lunch     2
225       16.27  2.50  Female    Yes   Fri   Lunch     2
226       10.09  2.00  Female    Yes   Fri   Lunch     2
227       20.45  3.00    Male     No   Sat  Dinner     4
228       13.28  2.72    Male     No   Sat  Dinner     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
230       24.01  2.00    Male    Yes   Sat  Dinner     4
231       15.69  3.00    Male    Yes   Sat  Dinner     3
232       11.61  3.39    Male     No   Sat  Dinner     2
233       10.77  1.47    Male     No   Sat  Dinner     2
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [118]:
type(tips)
# DataFrame: pandas의 기본적인 자료형태.
# -> 결국 NumPy기반.
# Structured Array에 기반.

pandas.core.frame.DataFrame

In [119]:
tips['day']

0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
5       Sun
6       Sun
7       Sun
8       Sun
9       Sun
10      Sun
11      Sun
12      Sun
13      Sun
14      Sun
15      Sun
16      Sun
17      Sun
18      Sun
19      Sat
20      Sat
21      Sat
22      Sat
23      Sat
24      Sat
25      Sat
26      Sat
27      Sat
28      Sat
29      Sat
       ... 
214     Sat
215     Sat
216     Sat
217     Sat
218     Sat
219     Sat
220     Fri
221     Fri
222     Fri
223     Fri
224     Fri
225     Fri
226     Fri
227     Sat
228     Sat
229     Sat
230     Sat
231     Sat
232     Sat
233     Sat
234     Sat
235     Sat
236     Sat
237     Sat
238     Sat
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: category
Categories (4, object): [Thur, Fri, Sat, Sun]

# Structured Array(key방식) 주의하도록.

In [121]:
tips.smoker
# ? 이건 되네ㅋㅋ
# key로도 attribute로도 접근 가능.

0       No
1       No
2       No
3       No
4       No
5       No
6       No
7       No
8       No
9       No
10      No
11      No
12      No
13      No
14      No
15      No
16      No
17      No
18      No
19      No
20      No
21      No
22      No
23      No
24      No
25      No
26      No
27      No
28      No
29      No
      ... 
214    Yes
215    Yes
216    Yes
217    Yes
218    Yes
219    Yes
220    Yes
221    Yes
222    Yes
223     No
224    Yes
225    Yes
226    Yes
227     No
228     No
229    Yes
230    Yes
231    Yes
232     No
233     No
234    Yes
235     No
236    Yes
237    Yes
238     No
239     No
240    Yes
241    Yes
242     No
243     No
Name: smoker, Length: 244, dtype: category
Categories (2, object): [Yes, No]

In [124]:
tips.size
# key 'size'가 아니라 진짜 사이즈를 불러버린다.(NumPy 메소드)

1708

In [ ]:
# NumPy에서 중요한거 2가지: shape, dtype

In [125]:
tips['size']

0      2
1      3
2      3
3      2
4      4
5      4
6      2
7      4
8      2
9      2
10     2
11     4
12     2
13     4
14     2
15     2
16     3
17     3
18     3
19     3
20     2
21     2
22     2
23     4
24     2
25     4
26     2
27     2
28     2
29     2
      ..
214    3
215    2
216    5
217    2
218    2
219    4
220    2
221    2
222    1
223    3
224    2
225    2
226    2
227    4
228    2
229    2
230    4
231    3
232    2
233    2
234    2
235    2
236    2
237    2
238    3
239    3
240    2
241    2
242    2
243    2
Name: size, Length: 244, dtype: int64

In [128]:
x

array([('Rex', 9, 81.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [133]:
x[0][0] = 100

In [134]:
x

array([('100', 9, 81.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [135]:
# 'name'부분에 무조건 문자열로 들어간다.
# 그래서 pandas에선 이름에 숫자를 넣을 수 있게.
# 그래서 인덱스로 못뽑아옴. -> 인덱스를 쓰는 법이 다르다.
tips.iloc[0]

total_bill     16.99
tip             1.01
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 0, dtype: object

In [136]:
tips.loc[0]

total_bill     16.99
tip             1.01
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 0, dtype: object

In [137]:
tips
#NumPy의 Structured Arrays
#pandas

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
6          8.77  2.00    Male     No   Sun  Dinner     2
7         26.88  3.12    Male     No   Sun  Dinner     4
8         15.04  1.96    Male     No   Sun  Dinner     2
9         14.78  3.23    Male     No   Sun  Dinner     2
10        10.27  1.71    Male     No   Sun  Dinner     2
11        35.26  5.00  Female     No   Sun  Dinner     4
12        15.42  1.57    Male     No   Sun  Dinner     2
13        18.43  3.00    Male     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
15        21.58  3.92    Male     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
17        16.29  3.71    Male     No   Sun  Dinner     3
18        16.97  3.50  Female     No   Sun  Dinner     3
19        20.65  3.35    Male     No   Sat  Dinner     3
20        17.92  4.08    Male     No   Sat  Dinner     2
21        20.29  2.75  Female     No   Sat  Dinner     2
22        15.77  2.23  Female     No   Sat  Dinner     2
23        39.42  7.58    Male     No   Sat  Dinner     4
24        19.82  3.18    Male     No   Sat  Dinner     2
25        17.81  2.34    Male     No   Sat  Dinner     4
26        13.37  2.00    Male     No   Sat  Dinner     2
27        12.69  2.00    Male     No   Sat  Dinner     2
28        21.70  4.30    Male     No   Sat  Dinner     2
29        19.65  3.00  Female     No   Sat  Dinner     2
..          ...   ...     ...    ...   ...     ...   ...
214       28.17  6.50  Female    Yes   Sat  Dinner     3
215       12.90  1.10  Female    Yes   Sat  Dinner     2
216       28.15  3.00    Male    Yes   Sat  Dinner     5
217       11.59  1.50    Male    Yes   Sat  Dinner     2
218        7.74  1.44    Male    Yes   Sat  Dinner     2
219       30.14  3.09  Female    Yes   Sat  Dinner     4
220       12.16  2.20    Male    Yes   Fri   Lunch     2
221       13.42  3.48  Female    Yes   Fri   Lunch     2
222        8.58  1.92    Male    Yes   Fri   Lunch     1
223       15.98  3.00  Female     No   Fri   Lunch     3
224       13.42  1.58    Male    Yes   Fri   Lunch     2
225       16.27  2.50  Female    Yes   Fri   Lunch     2
226       10.09  2.00  Female    Yes   Fri   Lunch     2
227       20.45  3.00    Male     No   Sat  Dinner     4
228       13.28  2.72    Male     No   Sat  Dinner     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
230       24.01  2.00    Male    Yes   Sat  Dinner     4
231       15.69  3.00    Male    Yes   Sat  Dinner     3
232       11.61  3.39    Male     No   Sat  Dinner     2
233       10.77  1.47    Male     No   Sat  Dinner     2
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

# pandas
## 직사각형 표 형태의 Data type
### 이게 중요한 이유? => 2차원의 데이터가 가장 효율적이기 때문에. => 분석 틀, 알고리즘은 2차원으로

In [138]:
tips[['day','time']]
#fancy indexing

day    time
0     Sun  Dinner
1     Sun  Dinner
2     Sun  Dinner
3     Sun  Dinner
4     Sun  Dinner
5     Sun  Dinner
6     Sun  Dinner
7     Sun  Dinner
8     Sun  Dinner
9     Sun  Dinner
10    Sun  Dinner
11    Sun  Dinner
12    Sun  Dinner
13    Sun  Dinner
14    Sun  Dinner
15    Sun  Dinner
16    Sun  Dinner
17    Sun  Dinner
18    Sun  Dinner
19    Sat  Dinner
20    Sat  Dinner
21    Sat  Dinner
22    Sat  Dinner
23    Sat  Dinner
24    Sat  Dinner
25    Sat  Dinner
26    Sat  Dinner
27    Sat  Dinner
28    Sat  Dinner
29    Sat  Dinner
..    ...     ...
214   Sat  Dinner
215   Sat  Dinner
216   Sat  Dinner
217   Sat  Dinner
218   Sat  Dinner
219   Sat  Dinner
220   Fri   Lunch
221   Fri   Lunch
222   Fri   Lunch
223   Fri   Lunch
224   Fri   Lunch
225   Fri   Lunch
226   Fri   Lunch
227   Sat  Dinner
228   Sat  Dinner
229   Sat  Dinner
230   Sat  Dinner
231   Sat  Dinner
232   Sat  Dinner
233   Sat  Dinner
234   Sat  Dinner
235   Sat  Dinner
236   Sat  Dinner
237   Sat  Dinner
238   Sat  Dinner
239   Sat  Dinner
240   Sat  Dinner
241   Sat  Dinner
242   Sat  Dinner
243  Thur  Dinner

[244 rows x 2 columns]

In [139]:
tips.day

0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
5       Sun
6       Sun
7       Sun
8       Sun
9       Sun
10      Sun
11      Sun
12      Sun
13      Sun
14      Sun
15      Sun
16      Sun
17      Sun
18      Sun
19      Sat
20      Sat
21      Sat
22      Sat
23      Sat
24      Sat
25      Sat
26      Sat
27      Sat
28      Sat
29      Sat
       ... 
214     Sat
215     Sat
216     Sat
217     Sat
218     Sat
219     Sat
220     Fri
221     Fri
222     Fri
223     Fri
224     Fri
225     Fri
226     Fri
227     Sat
228     Sat
229     Sat
230     Sat
231     Sat
232     Sat
233     Sat
234     Sat
235     Sat
236     Sat
237     Sat
238     Sat
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: category
Categories (4, object): [Thur, Fri, Sat, Sun]

In [140]:
type(tips.day)
# DataFrame이 아니라 Series

pandas.core.series.Series

In [142]:
tips.tip + 5
#Broadcasting: 타입 안맞춰도 대충 알아서 해줌.

0       6.01
1       6.66
2       8.50
3       8.31
4       8.61
5       9.71
6       7.00
7       8.12
8       6.96
9       8.23
10      6.71
11     10.00
12      6.57
13      8.00
14      8.02
15      8.92
16      6.67
17      8.71
18      8.50
19      8.35
20      9.08
21      7.75
22      7.23
23     12.58
24      8.18
25      7.34
26      7.00
27      7.00
28      9.30
29      8.00
       ...  
214    11.50
215     6.10
216     8.00
217     6.50
218     6.44
219     8.09
220     7.20
221     8.48
222     6.92
223     8.00
224     6.58
225     7.50
226     7.00
227     8.00
228     7.72
229     7.88
230     7.00
231     8.00
232     8.39
233     6.47
234     8.00
235     6.25
236     6.00
237     6.17
238     9.67
239    10.92
240     7.00
241     7.00
242     6.75
243     8.00
Name: tip, Length: 244, dtype: float64

In [143]:
# Reduction
tips.tip.sum()
#NumPy기반이라 다된다. 
# NumPy를 알면 pandas의 어려움은 줄어든다.

731.5799999999999

In [ ]:
# array는 방향이 없다.

In [144]:
tips.iloc[3]
#index location

total_bill     23.68
tip             3.31
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 3, dtype: object

In [146]:
tips.loc[3]
#보기에 같아보이지만, 슬라이스를 하면 다르다

total_bill     23.68
tip             3.31
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 3, dtype: object

In [148]:
tips.iloc[3:6] #6 미포함

total_bill   tip     sex smoker  day    time  size
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4

In [149]:
tips.loc[3:6] #6포함

total_bill   tip     sex smoker  day    time  size
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2

# NumPy indexing
# , ... 마스킹 조건 FancyIndexing

In [152]:
tips.loc[3,'day'] #이름

'Sun'

In [154]:
tips.loc[3:6,'day']

3    Sun
4    Sun
5    Sun
6    Sun
Name: day, dtype: category
Categories (4, object): [Thur, Fri, Sat, Sun]

In [155]:
tips.loc[3:6,['day','smoker']]

day smoker
3  Sun     No
4  Sun     No
5  Sun     No
6  Sun     No

In [157]:
tips.iloc[3:6,:-2]

total_bill   tip     sex smoker  day
3       23.68  3.31    Male     No  Sun
4       24.59  3.61  Female     No  Sun
5       25.29  4.71    Male     No  Sun

In [159]:
tips[['tip']]

tip
0    1.01
1    1.66
2    3.50
3    3.31
4    3.61
5    4.71
6    2.00
7    3.12
8    1.96
9    3.23
10   1.71
11   5.00
12   1.57
13   3.00
14   3.02
15   3.92
16   1.67
17   3.71
18   3.50
19   3.35
20   4.08
21   2.75
22   2.23
23   7.58
24   3.18
25   2.34
26   2.00
27   2.00
28   4.30
29   3.00
..    ...
214  6.50
215  1.10
216  3.00
217  1.50
218  1.44
219  3.09
220  2.20
221  3.48
222  1.92
223  3.00
224  1.58
225  2.50
226  2.00
227  3.00
228  2.72
229  2.88
230  2.00
231  3.00
232  3.39
233  1.47
234  3.00
235  1.25
236  1.00
237  1.17
238  4.67
239  5.92
240  2.00
241  2.00
242  1.75
243  3.00

[244 rows x 1 columns]

In [ ]:
#열 뽑아오는 방법 3가지
# key방식(['key']) : 
# attribute방식(.key()) : 공백있는 이름 등에서 문제.
# Fancyindexing

#상황에 맞추어 적절하게 쓴다.

In [ ]:
# 행 가져오는 방식 2가지
# .iloc : index를 갖고온다 (끝에있는거 포함 안함)
# .loc : 이름을 맞춰서 갖고온다(끝까지 포함)

In [160]:
%time tips.tip

Wall time: 0 ns


0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
5      4.71
6      2.00
7      3.12
8      1.96
9      3.23
10     1.71
11     5.00
12     1.57
13     3.00
14     3.02
15     3.92
16     1.67
17     3.71
18     3.50
19     3.35
20     4.08
21     2.75
22     2.23
23     7.58
24     3.18
25     2.34
26     2.00
27     2.00
28     4.30
29     3.00
       ... 
214    6.50
215    1.10
216    3.00
217    1.50
218    1.44
219    3.09
220    2.20
221    3.48
222    1.92
223    3.00
224    1.58
225    2.50
226    2.00
227    3.00
228    2.72
229    2.88
230    2.00
231    3.00
232    3.39
233    1.47
234    3.00
235    1.25
236    1.00
237    1.17
238    4.67
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [162]:
%time tips['tip']

Wall time: 0 ns


0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
5      4.71
6      2.00
7      3.12
8      1.96
9      3.23
10     1.71
11     5.00
12     1.57
13     3.00
14     3.02
15     3.92
16     1.67
17     3.71
18     3.50
19     3.35
20     4.08
21     2.75
22     2.23
23     7.58
24     3.18
25     2.34
26     2.00
27     2.00
28     4.30
29     3.00
       ... 
214    6.50
215    1.10
216    3.00
217    1.50
218    1.44
219    3.09
220    2.20
221    3.48
222    1.92
223    3.00
224    1.58
225    2.50
226    2.00
227    3.00
228    2.72
229    2.88
230    2.00
231    3.00
232    3.39
233    1.47
234    3.00
235    1.25
236    1.00
237    1.17
238    4.67
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [163]:
%time tips[['tip']]

Wall time: 1.98 ms


tip
0    1.01
1    1.66
2    3.50
3    3.31
4    3.61
5    4.71
6    2.00
7    3.12
8    1.96
9    3.23
10   1.71
11   5.00
12   1.57
13   3.00
14   3.02
15   3.92
16   1.67
17   3.71
18   3.50
19   3.35
20   4.08
21   2.75
22   2.23
23   7.58
24   3.18
25   2.34
26   2.00
27   2.00
28   4.30
29   3.00
..    ...
214  6.50
215  1.10
216  3.00
217  1.50
218  1.44
219  3.09
220  2.20
221  3.48
222  1.92
223  3.00
224  1.58
225  2.50
226  2.00
227  3.00
228  2.72
229  2.88
230  2.00
231  3.00
232  3.39
233  1.47
234  3.00
235  1.25
236  1.00
237  1.17
238  4.67
239  5.92
240  2.00
241  2.00
242  1.75
243  3.00

[244 rows x 1 columns]

In [ ]:
# fancyindexing이 제일 빠름.

In [166]:
%time tips.at[3,'time']

Wall time: 0 ns


'Dinner'

In [165]:
%time tips.loc[3,'tip']

Wall time: 0 ns


3.31

In [167]:
%time tips.iat[3,5]

Wall time: 0 ns


'Dinner'

In [ ]:
# NumPy : '벡터 기반'으로 데이터를 처리하는 Library

In [ ]:
# pandas : EDA 전처리(데이터 랭글링/먼징 Tool)
# 데이터 먼징: 데이터를 불러오고, 합치고, 간단한 전처리 하고 기초 분석까지 하는것.
# 데이터 랭글링: 

In [ ]:
# http://archive.ics.uci.edu/ml/index.php